#ifndef _PG_THRIFT_H_
#define _PG_THRIFT_H_

#include <postgres.h>
#include <port.h>


#define THRIFT_RESULT_MAX_FIELDS 256

#define PG_THRIFT_BINARY_BOOL 2
#define PG_THRIFT_BINARY_BYTE 3
#define PG_THRIFT_BINARY_DOUBLE 4
#define PG_THRIFT_BINARY_INT16 6
#define PG_THRIFT_BINARY_INT32 8
#define PG_THRIFT_BINARY_INT64 10
#define PG_THRIFT_BINARY_STRING 11
#define PG_THRIFT_BINARY_STRUCT 12
#define PG_THRIFT_BINARY_MAP 13
#define PG_THRIFT_BINARY_SET 14
#define PG_THRIFT_BINARY_LIST 15

#define PG_THRIFT_COMPACT_BOOL 2
#define PG_THRIFT_COMPACT_BYTE 3
#define PG_THRIFT_COMPACT_DOUBLE 7
#define PG_THRIFT_COMPACT_INT16 4
#define PG_THRIFT_COMPACT_INT32 5
#define PG_THRIFT_COMPACT_INT64 6
#define PG_THRIFT_COMPACT_STRING 8
#define PG_THRIFT_COMPACT_STRUCT 12
#define PG_THRIFT_COMPACT_MAP 11
#define PG_THRIFT_COMPACT_SET 10
#define PG_THRIFT_COMPACT_LIST 9

#define BYTE_LEN 4
#define PG_THRIFT_TYPE_LEN 1
#define PG_THRIFT_FIELD_LEN 2
#define DOUBLE_LEN 8
#define INT16_LEN 2
#define INT32_LEN 4
#define INT64_LEN 8
#define LIST_LEN 4
#define BOOL_LEN 1
#define FIELD_LEN 2
#define MAX_JSON_STRING_SIZE 1024

#endif // _PG_THRIFT_H_
